# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'TinkoffExpress' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TinkoffExpress
    pod 'SnapKit', '~> 5.0.0'
    pod 'SwiftLint', '~> 0.46.2'

end
